# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki
language: c

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap
install:
    - ./travis-tool.sh install_deps
    - ./travis-tool.sh install_bioc_deps
    - ./travis-tool.sh install_bioc Biobase
    - ./travis-tool.sh install_bioc repmis
    - ./travis-tool.sh install_bioc vsn
    - ./travis-tool.sh install_bioc colonCA
    - ./travis-tool.sh install_bioc fission
    - ./travis-tool.sh install_r ggplot2
    - ./travis-tool.sh install_r reshape2
script: ./travis-tool.sh run_tests

